"""
omega60.arwen
=============
Step 7 – Sample rays for ARWEN.

ARWEN is a 2-D radiation-hydrodynamics code (Velarde & Ogando, UPM,
Spain) used to simulate ICF implosions.  Before running ARWEN, a ray
file must be prepared that describes the laser beams as a discrete set
of rays entering the computational domain.

ARWEN ray-file format (ASCII)
------------------------------
Line 1  : ``# ARWEN ray file — OMEGA 60 — generated by omega60 package``
Line 2  : metadata (wavelength [m], pulse duration [s], total energy [J])
Line 3  : ``n_rays`` (integer)
Lines 4…: one ray per line::

    x_0  y_0  z_0  dx  dy  dz  energy_J  t_start_s  t_end_s

where (x0, y0, z0) is the ray origin [m] on a sphere of radius
``launch_radius_m`` (default: target radius × 1.5), (dx, dy, dz) is
the unit direction vector pointing *inward* (toward the target), and
energy_J is the energy carried by the ray.

This module generates a separate ARWEN-format set of rays that is
optimised for the code's structured-grid geometry: rays are *uniformly
re-sampled* so that the flux through each grid cell is approximately
equal (stratified sampling on a launch sphere just outside the target).
"""

import numpy as np
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .beams import Omega60Laser
    from .target import SphericalTarget


class ArwenRayWriter:
    """
    Generate and write ARWEN-compatible ray data.

    Parameters
    ----------
    laser : Omega60Laser
        Laser configuration.
    target : SphericalTarget
        Target geometry (provides target radius for launch sphere).
    n_rays : int
        Total number of rays to generate across all 60 beams.
        Default: 60 000 (1 000 per beam).
    launch_radius_factor : float
        The rays are launched from a sphere of radius
        ``launch_radius_factor × target.radius_m``.  Default: 1.5.
    seed : int or None
        Random seed for reproducibility.
    """

    HEADER_LINE = "# ARWEN ray file — OMEGA 60 — generated by omega60 package"

    def __init__(
        self,
        laser,
        target,
        n_rays: int = 60_000,
        launch_radius_factor: float = 1.5,
        seed: int | None = None,
    ) -> None:
        self.laser = laser
        self.target = target
        self.n_rays = n_rays
        self.launch_radius_factor = launch_radius_factor
        self.launch_radius = launch_radius_factor * target.radius_m

        rng = np.random.default_rng(
            seed if seed is not None else laser.seed
        )
        self.rays = self._sample_arwen_rays(rng)

    # ------------------------------------------------------------------
    # Ray generation
    # ------------------------------------------------------------------

    def _sample_arwen_rays(self, rng: np.random.Generator) -> dict:
        """
        Sample rays uniformly distributed across all beams.

        For each ray the origin is placed on the launch sphere at the
        point where the beam chief ray crosses it.  The direction is
        exactly the beam's chief-ray direction (toward target centre).
        Uniform disk sampling within each beam's solid-angle footprint
        on the launch sphere provides sub-beam spatial coverage.

        Returns
        -------
        dict with keys:
            ``origins``    – (N, 3) [m]
            ``directions`` – (N, 3) unit vectors
            ``energies``   – (N,)  [J]
            ``beam_ids``   – (N,)  int32
            ``t_start``    – (N,)  [s]  = 0 (pulse start)
            ``t_end``      – (N,)  [s]  = pulse_duration_s
        """
        from .rays import _random_disk_uniform, _build_local_frame

        rays_per_beam = self.n_rays // self.laser.NUM_BEAMS
        n_total = rays_per_beam * self.laser.NUM_BEAMS
        energy_per_ray = self.laser.total_energy_J / n_total

        # Launch sphere radius (slightly larger than target)
        R_launch = self.launch_radius

        # Beam half-angle at launch sphere
        # tan(half_angle) ≈ beam_radius / distance_to_lens
        # At the launch sphere, the beam footprint radius:
        #   r_footprint = beam_radius × R_launch / target_distance
        r_footprint = (
            self.laser.beam_radius_m
            * R_launch
            / self.laser.target_distance_m
        )

        origins = np.empty((n_total, 3), dtype=np.float64)
        directions = np.empty((n_total, 3), dtype=np.float64)
        energies = np.full(n_total, energy_per_ray, dtype=np.float64)
        beam_ids = np.empty(n_total, dtype=np.int32)
        t_start = np.zeros(n_total, dtype=np.float64)
        t_end = np.full(n_total, self.laser.pulse_duration_s, dtype=np.float64)

        for i in range(self.laser.NUM_BEAMS):
            sl = slice(i * rays_per_beam, (i + 1) * rays_per_beam)

            beam_axis = self.laser.beam_axes[i]           # outward unit vector
            chief_origin = beam_axis * R_launch            # on launch sphere
            u_hat, v_hat = _build_local_frame(beam_axis)

            # Uniform disk sampling within beam footprint on launch sphere
            disk = _random_disk_uniform(rays_per_beam, rng)  # (n, 2)
            offsets = (
                disk[:, 0:1] * r_footprint * u_hat
                + disk[:, 1:2] * r_footprint * v_hat
            )
            ray_origins = chief_origin + offsets  # (n, 3)

            # Snap origins onto the launch sphere
            norms = np.linalg.norm(ray_origins, axis=1, keepdims=True)
            ray_origins = ray_origins / norms * R_launch

            # Directions: each ray points toward the target centre
            to_target = -ray_origins
            norms2 = np.linalg.norm(to_target, axis=1, keepdims=True)
            ray_dirs = to_target / norms2

            origins[sl] = ray_origins
            directions[sl] = ray_dirs
            beam_ids[sl] = i

        return {
            "origins": origins,
            "directions": directions,
            "energies": energies,
            "beam_ids": beam_ids,
            "t_start": t_start,
            "t_end": t_end,
        }

    # ------------------------------------------------------------------
    # File I/O
    # ------------------------------------------------------------------

    def write(self, path: str | Path) -> None:
        """
        Write the ARWEN ray file to *path*.

        Parameters
        ----------
        path : str or Path
            Output file path (typically ``*.ray`` or ``*.txt``).
        """
        path = Path(path)
        rays = self.rays
        n = rays["origins"].shape[0]

        with open(path, "w") as fh:
            fh.write(self.HEADER_LINE + "\n")
            fh.write(
                f"# wavelength_m={self.laser.wavelength_m:.6e}  "
                f"pulse_duration_s={self.laser.pulse_duration_s:.6e}  "
                f"total_energy_J={self.laser.total_energy_J:.6e}\n"
            )
            fh.write(f"{n}\n")
            for k in range(n):
                ox, oy, oz = rays["origins"][k]
                dx, dy, dz = rays["directions"][k]
                e = rays["energies"][k]
                t0 = rays["t_start"][k]
                t1 = rays["t_end"][k]
                fh.write(
                    f"{ox: .8e}  {oy: .8e}  {oz: .8e}  "
                    f"{dx: .8e}  {dy: .8e}  {dz: .8e}  "
                    f"{e:.8e}  {t0:.8e}  {t1:.8e}\n"
                )

    def summary(self) -> str:
        """Return a human-readable summary of the generated ARWEN ray set."""
        rays = self.rays
        d = rays["directions"]
        # Check that all directions are inward (dot product with position < 0)
        inward = np.einsum("ij,ij->i", rays["origins"], d)
        lines = [
            "=" * 55,
            "  ARWEN Ray File — Summary",
            "=" * 55,
            f"  Number of rays         : {rays['origins'].shape[0]:,}",
            f"  Launch sphere radius   : {self.launch_radius*1e6:.1f} µm",
            f"  Energy per ray         : {rays['energies'][0]:.4e} J",
            f"  Total energy           : {rays['energies'].sum():.4e} J",
            f"  All rays inward        : {(inward < 0).all()}",
            "=" * 55,
        ]
        return "\n".join(lines)

    def __repr__(self) -> str:
        return (
            f"ArwenRayWriter(n_rays={self.n_rays}, "
            f"launch_radius={self.launch_radius:.3e} m)"
        )
